full_rebuild: true
name: "Azure Red Hat OpenShift Workshop"
tracking: "aroworkshop"
author: Microsoft
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: CommonMarkGhPages
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
