full_rebuild: true
name: "Red Hat OCP Workshop"
tracking: "ocpworkshop"
author: brianstinehart
encoding: utf-8
host: 0.0.0.0
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
